#!/usr/bin/env bash
# sync-agent-docs.sh — Copy primkit docs that agents need into clawson-config.
#
# Usage:
#   bash scripts/sync-agent-docs.sh [CLAWSON_CONFIG_DIR]
#
# Default destination: ~/development/andresvio/clawson-config
# Override by passing a path or setting CLAWSON_CONFIG_DIR env var.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${1:-${CLAWSON_CONFIG_DIR:-$HOME/development/andresvio/clawson-config}}"
DEST_BASE="$DEST/.openclaw/docs-and-guides/primkit"

if [[ ! -d "$DEST" ]]; then
  echo "error: destination not found: $DEST" >&2
  exit 1
fi

copy() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
  echo "  copied: docs/$(basename "$src") → ${dst#$DEST/}"
}

echo "syncing primkit agent docs → $DEST_BASE"

# agent-reference.md is auto-generated by 'make docs' — most critical to keep in sync.
copy "$REPO_ROOT/docs/agent-reference.md" "$DEST_BASE/reference.md"
copy "$REPO_ROOT/docs/configuration.md"   "$DEST_BASE/configuration.md"
copy "$REPO_ROOT/docs/knowledgeprim.md"   "$DEST_BASE/knowledgeprim/knowledgeprim-guide.md"
copy "$REPO_ROOT/docs/queueprim.md"       "$DEST_BASE/queueprim/queueprim-guide.md"

echo "done."
