name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write  # keyless cosign signing via Sigstore OIDC

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Configure private module access
        run: git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPRIVATE: github.com/propifly/*
